dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    secure: a3+NNOdHDOfci7JxpL3hma0/RZ6WzrGwGYtA9ll4GsRE6nPrFH5Qh6+WoO1SLOuEIzpcUjvUPE5dZYDFovGFxUXt0AJfmnjoYmO6/D/IrJJ7Cfm1Fv22ru5tvNbwkxuZeu44RzcD6qr9rLa4xlYvbfwC7YBG9n8uFHnNz4Yu3Sxv+4o+WGMgJngK62j1H+i8LDSN42/PBsEUVNv+prMX0rXvkSF7bVLFLDUxArtLqX4kmbJGlbROAs1WirOnl2Rt227vzjng3qOv+3OCdFVAGkxNIUhhENgxwxiIZ0fXvZPEr/E8lAVVtPh4Xc1jfcADcdALstLczFYbfrTt1+y9GLZu/MArXUKodt4b1Vor+ta1mFEJreXijtHt+pPIqAY8v3Lw+e3+vgiebgaf0FSfWZZWxlWUWUWON0r0zvniJRKbKyzUMNmbkQ5kPQSSr/lz+0zHcNe6FsNTeuegMufN5rfgiXW+1KsxQjgHR3k97FRdtYMk/U60OV1XW7aMj9CY6TF2Bn788Fq1oCwic9hizORpGIZKxqUWYYzZ6KDlnfZ6/iUkz56MvrmMUd4Eh8NBSI+ZARgO5gWmeoxGqiphZAy4GXunx6TRblAAYL0t5puYLYjOnumHLwVZol0jfc8aCm87GaZm905ueFOulk0tvkMIPaZT0x/V6nLDlMOkZjM=
