dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: kgak+DklKmE45FjK8UoVyQHPqN2Dkwj28Dvd9BFIhXf5+A/XRcK8bHstf7aUNMfEKN5SrnKW7fVqb2soY83swq18+uApTV+cLWshRem0LoM5G4DkU5zPArsqSr5Kl0MEdR9Ioyur30L8+xkTfp85oiTJXLWDMHlAu8Jfp5qlwzN1oML7c5zRDYqwQrjTq0HvwP0+t0H8Ynl6ICrYjiCO4SBJEd6yDbO5QiGZ/GHqxlH1AoXGoTLR2VG2+qlWrg+efpR0s51S3q4cV9q3ef7nES2PX/paJ9syRCUGjEEWmCAulKk2bv/yBOdTSZoj7A39Z0+de4nBAbpyRV2YJTLf5KRTRx3IGyppF7wSXPZ0ho3jkhfXNu64s0tl6ZP2weV8LCmdqgVIy4GgvgP35lpwigemb3o0lkPljeS51ndC/VLqlNlJjNwsnieK8YB9GguqPj6ZJvpWQphA3sdM3AAi7QvCeheG0FRWdwFPn7Tw+rNL/Rq0RpJyC7v4HSuBUTgz8SOmWIGY/xphC1V0w5P9ltnSKb6uWTdtam+1VJ84osKld9JIrdMGG4UJ0NHyAyL7yIbO5UV/4kmkj4DE3KcEaWbn73Z7JDqQCsU8G8mOJdQCNK74uaP/cglu8XKbFZesnS9y++rzCMejZ3VCRQErCMNGBRRgS3Ts4ch5/Q12iUI=
